import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* Added global dark background and white text here */}
      <body className="min-h-full flex flex-col text-white">
        {/* --- NAVIGATION BAR --- */}
        <nav className="w-full flex items-center justify-between px-8 py-6 max-w-7xl mx-auto">
          {/* Logo */}
          <Link href="/">
            <Image
              src="/r-logo.png"
              alt="R Logo"
              width={40}
              height={40}
              className="cursor-pointer"
            />
          </Link>

          {/* Desktop Links */}
          <div className="flex items-center gap-14 text-m text-secondary ">
            <Link href="/#services" className="navbar-link">
              Services
            </Link>
            <Link href="/#about" className="navbar-link">
              About Me
            </Link>
            <Link href="/portfolio" className="navbar-link">
              Portfolio
            </Link>
            <Link href="/#pricing" className="navbar-link">
              Pricing
            </Link>
            <Link href="/blog" className="navbar-link">
              Blog
            </Link>
          </div>

          {/* Contact Button */}
          <div className="flex justify-end">
            <Link href="#contact" className="hidden md:flex btn-get-in-touch">
              Get in touch
            </Link>
          </div>
        </nav>
        {/* --- END NAVIGATION BAR --- */}

        {/* This is where your page content gets injected */}
        {children}

        {/* --- FOOTER --- */}
        <Footer />
      </body>
    </html>
  );
}
